/**
 * Country Constants
 *
 * Country code to name mapping for common countries
 * Used throughout the application for geographic data display
 */

export const COUNTRY_NAMES: Record<string, string> = {
  USA: "United States",
  GBR: "United Kingdom",
  DEU: "Germany",
  FRA: "France",
  JPN: "Japan",
  CHN: "China",
  IND: "India",
  BRA: "Brazil",
  CAN: "Canada",
  AUS: "Australia",
  RUS: "Russia",
  ESP: "Spain",
  ITA: "Italy",
  NLD: "Netherlands",
  KOR: "South Korea",
  MEX: "Mexico",
  CHE: "Switzerland",
  SWE: "Sweden",
  NOR: "Norway",
  DNK: "Denmark",
  FIN: "Finland",
  POL: "Poland",
  BEL: "Belgium",
  AUT: "Austria",
  NZL: "New Zealand",
  SGP: "Singapore",
  THA: "Thailand",
  IDN: "Indonesia",
  MYS: "Malaysia",
  PHL: "Philippines",
  VNM: "Vietnam",
  ARE: "UAE",
  SAU: "Saudi Arabia",
  ISR: "Israel",
  ZAF: "South Africa",
  EGY: "Egypt",
  TUR: "Turkey",
  GRC: "Greece",
  PRT: "Portugal",
  CZE: "Czech Republic",
  HUN: "Hungary",
  ROU: "Romania",
  BGR: "Bulgaria",
  HRV: "Croatia",
  SVN: "Slovenia",
  SVK: "Slovakia",
  EST: "Estonia",
  LVA: "Latvia",
  LTU: "Lithuania",
  LUX: "Luxembourg",
  MLT: "Malta",
  CYP: "Cyprus",
  ISL: "Iceland",
  IRL: "Ireland",
  ARG: "Argentina",
  CHL: "Chile",
  COL: "Colombia",
  PER: "Peru",
  URY: "Uruguay",
  ECU: "Ecuador",
  BOL: "Bolivia",
  PRY: "Paraguay",
  VEN: "Venezuela",
  UKR: "Ukraine",
  BLR: "Belarus",
  MDA: "Moldova",
  GEO: "Georgia",
  ARM: "Armenia",
  AZE: "Azerbaijan",
  KAZ: "Kazakhstan",
  UZB: "Uzbekistan",
  KGZ: "Kyrgyzstan",
  TJK: "Tajikistan",
  TKM: "Turkmenistan",
  MNG: "Mongolia",
};
